### PR TITLE
angular-focus-caret

### PR DESCRIPTION
**Pull request by bholloway**
Getting a problem with InternetExplorer.

When focussing a text input that has text already in it, the caret would normally go to the end of the field. This is the case in Chrome, for instance. However in IE11 the caret does not reliably do this.

I am proposing an additional attribute `focus-caret-index` to explicitly control location of the caret. It is a general feature but solves the specific IE11 problem. Refer to the updated `readme.md` for details.

This pull request has been tested in Chrome and IE11.

Please let me know your thoughts. I am currently pointing bower to my own repo and would like to resume using yours asap.

### CODE REVIEW

**Comment by hiebj** [comment]
So, personally, I'd create a new directive for this. In fact, there's a very similar directive I already created for my own project called [ng-autoselect](https://github.com/hiebj/ng-autoselect). It's friendly and plays nice with `focus-if` - it's basically completely unaware of it and sets the selection regardless of how the field is focused, so of course it works when the focus is set by focus-if.

If you really only want to set caret position when it's triggered by `focus-if`, you could absolutely interrogate `$attrs` in your directive `link` function and see if focus-if is defined. I'm not trying to shut down your idea by any stretch and if there is a good argument for it I'm happy to make improvements - but to the extent possible I like to keep things simple and give directives single responsibilities. From an implementation perspective, it would look exactly the same as adding the code here - except that you'd also be able to use your directive **without** `focus-if`, making it more versatile.

**Comment by bholloway** [comment]
Ok thats really nice. Let me try that out before I cancel this this PR.

Completely agree with your argument for single responsibility.

That said, a comment in the `readme.md` would definitely help anyone working with IE. But I would raise a different PR.

**Comment by hiebj** [comment]
Sounds awesome. If you end up creating that directive and write up some nice documentation for it, I'll even totally link to your repo in the README and cite it as a fix for IE silliness. I've been planning to link to `ng-autoselect` for some time now but I want to make sure it's well documented before sending people over there, and I haven't been able to force myself to sit down and write it up.

**Comment by bholloway** [comment]
Got that implemented as [angular-focus-caret](https://www.npmjs.com/package/angular-focus-caret).

For my purposes I just use `focus-caret` it in addition to `ng-focus-if`. When the input receives focus, the caret is always at the end of the existing content, avoiding some IE edge cases. The directive allows explicit indexes which I have tested but are not relevant to my current use case.

I am not an expert in writing directives so please let me know if you see any problems.

Note the way the module is exported as its name. This seems to be the defacto standard, at least for the common-js angular packages I have seen. Would you agree?

**Comment by hiebj** [comment]
At a glance it looks great to me. From what I've seen everyone's Angular style varies. It depends on what build tools you plan to cater to and preferred code style. I recognize some of [johnpapa](https://github.com/johnpapa/angular-styleguide)'s style guide suggestions in there. My own style is loosely based on his with a lot of my own decisions mixed in; like so many other things I've had this idea in my head that I'll write my own style guide at some point, but just haven't had the time.

I almost always export the directive module by name as you have. I don't typically namespace things with my name like `hiebj-focus-if`... that's something for the bigger players like the `angular-ui` team. The only other way I'd go about it would be when publishing a set of related directives; for instance I have an as-yet unpublished group of directives related to file upload inputs that I might publish under one module.

The only suggestion I have would be to write unit tests. But I can't honestly criticize about that since most of my directives are untested and undocumented, `focus-if` being the prime exception. Yet another thing I'd do if I had time.

If you want to see another example of a directive I wrote recently that's a little more complicated, check out [ng-attach](https://github.com/hiebj/ng-attach) (name subject to change). Needs documentation and testing but it's pretty useful.

**Pull request closed without merging**
