### PR TITLE
Dependency injection compatible with minifiers

### PR DESCRIPTION
**Pull request by Richter1991**
Dependency injection compatible with minifiers

### CODE REVIEW

**Comment by bholloway** [comment]
I suggest you run an pre-minifier, such as [ng-annotate](https://www.npmjs.com/package/ng-annotate). There are implementations for grunt, gulp, and many other systems.

**Comment by hiebj** [comment]
Agree totally with bholloway. As much as possible it's my belief that your code should not have to cater to your build process, but rather the other way around - your build process should cater to your code. Workflow tools like gulp and grunt are intended to make your life easier as a developer and allow you to develop "naturally". Even if you aren't using something like gulp or grunt, and you're just using the shell to build your app, you can add a call to `ng-annotate` in your build script.

Out of curiosity, why are you minifying the file yourself? The .min.js file is exactly the same code except it has already had the `$inject` property appended by `ng-annotate` in my gulp build. I can't think of a reason to use the unminified file. Heck, if you wanted to, you could run the minified file through your minifier again. It shouldn't break anything.

**Comment by ClementRivaille** [comment]
It can still be problematic if a project concatenates and minifies all its bower dependencies. Fortunately, bower is able to filter libraries, and thus can ignore any other files than the .min.js one.
It has to be declared in the _bower.json_ of every projects using ng-focus-if, though. So I also think that having the injection even in the source itself would simplify the build process without being too unnatural.

**Comment by JohnColvin** [comment]
:+1: for annotating the unminified source.

> Out of curiosity, why are you minifying the file yourself?

In a rails project I work on, we typically include the unminified source and serve the unminified source in our dev environment. If there's an error, we can see the line that it comes from. This worked fine for me in dev, When it went to a staging environment and was minified, the lack of annotations caused a bug. We use [ng-annotate-rails](https://github.com/kikonen/ngannotate-rails#rails-configuration-options) to annotate our own code. It excludes vendor assets by default.

Regardless of any particular build process, I think annotating makes sense if you're distributing your code to be used by others. All angular core libraries are distributed with annotations in their unminified form, as well as every other angular community package I've used so far.

**Comment by hiebj** [comment]
Fixed by https://github.com/hiebj/ng-focus-if/pull/15#issuecomment-157502064

**Pull request closed without merging**
